update

diff --git a/Personal-ArchFiery b/Personal-ArchFiery
--- a/Personal-ArchFiery
+++ b/Personal-ArchFiery
@@ -3,108 +3,77 @@
 clear
 
 #Main Start
-#
-# Exit on CTRL + c
-ctrl_c() {
-  err "Keyboard Interrupt detected, leaving..."
-  exit $FAILURE
-}
+# #
+# # Exit on CTRL + c
+# ctrl_c() {
+#   err "Keyboard Interrupt detected, leaving..."
+#   exit $FAILURE
+# }
 
-trap ctrl_c 2
+# trap ctrl_c 2
 
-# check exit status
-check() {
-  es=$1
-  func="$2"
-  info="$3"
+# # check exit status
+# check() {
+#   es=$1
+#   func="$2"
+#   info="$3"
 
-  if [ "$es" -ne 0 ]
-  then
-    echo
-    warn "Something went wrong with $func. $info."
-    sleep 5
-  fi
-}
+#   if [ "$es" -ne 0 ]
+#   then
+#     echo
+#     warn "Something went wrong with $func. $info."
+#     sleep 5
+#   fi
+# }
 
-# check boot mode
-check_boot_mode() {
-  efivars=$(ls /sys/firmware/efi/efivars > /dev/null 2>&1; echo $?)
-  if [ "$efivars" -eq "0" ]
-  then
-     BOOT_MODE="uefi"
-  fi
+# # check boot mode
+# check_boot_mode() {
+#   efivars=$(ls /sys/firmware/efi/efivars > /dev/null 2>&1; echo $?)
+#   if [ "$efivars" -eq "0" ]
+#   then
+#      BOOT_MODE="uefi"
+#   fi
 
-  return $SUCCESS
-}
+#   return $SUCCESS
+# }
 
-# check for environment issues
-check_env() {
-  if [ -f '/var/lib/pacman/db.lck' ]
-  then
-    err 'pacman locked - Please remove /var/lib/pacman/db.lck'
-  fi
-}
+# # check for environment issues
+# check_env() {
+#   if [ -f '/var/lib/pacman/db.lck' ]
+#   then
+#     err 'pacman locked - Please remove /var/lib/pacman/db.lck'
+#   fi
+# }
 
-# check user id
-check_uid() {
-  if [ "$(id -u)" != '0' ]
-  then
-    err 'You must be root to run the BlackArch installer!'
-  fi
+# # check user id
+# check_uid() {
+#   if [ "$(id -u)" != '0' ]
+#   then
+#     err 'You must be root to run the BlackArch installer!'
+#   fi
 
-  return $SUCCESS
-}
+#   return $SUCCESS
+# }
 
-# check for internet connection
-check_inet_connection() {
-  title 'Network Setup > Connection Check'
-  wprintf '[+] Checking for Internet connection...'
+# # check for internet connection
+# check_inet_connection() {
+#   title 'Network Setup > Connection Check'
+#   wprintf '[+] Checking for Internet connection...'
 
-  if ! curl -s https://www.duckduckgo.com/ > $VERBOSE
-  then
-    err 'No Internet connection! Check your network (settings).'
-    exit $FAILURE
-  fi
-}
+#   if ! curl -s https://www.duckduckgo.com/ > $VERBOSE
+#   then
+#     err 'No Internet connection! Check your network (settings).'
+#     exit $FAILURE
+#   fi
+# }
 
-main(){
-  # do some ENV checks
-  sleep_clear 0
-  check_uid
-  check_env
-  check_boot_mode
-}
-
- arch=''
-
-  bluetooth='bluez-hid2hci'
-
-  editor='hexedit '
-
-  filesystem='cifs-utils dmraid dosfstools exfat-utils f2fs-tools
-  gpart gptfdisk mtools nilfs-utils ntfs-3g partclone parted partimage'
-
-  fonts='ttf-dejavu ttf-indic-otf ttf-liberation xorg-fonts-misc'
-
-  hardware='amd-ucode intel-ucode'
-
-  kernel='linux-headers-lts'
-
-  misc='acpi alsa-utils b43-fwcutter bash-completion bc cmake ctags expac
-  feh git gpm haveged hdparm htop inotify-tools ipython irssi
-  linux-atm lsof mercurial mesa mlocate moreutils mpv p7zip rsync
-  rtorrent screen scrot smartmontools strace tmux udisks2 unace unrar
-  unzip upower usb_modeswitch usbutils zip zsh'
-
-  network='atftp bind-tools bridge-utils curl darkhttpd dhclient dhcpcd dialog
-  dnscrypt-proxy dnsmasq dnsutils fwbuilder gnu-netcat ipw2100-fw ipw2200-fw iw
-  iwd lftp nfs-utils ntp openconnect openssh openvpn ppp pptpclient rfkill
-  rp-pppoe socat vpnc wget wireless_tools wpa_supplicant wvdial xl2tpd'
-
-  xorg='rxvt-unicode xf86-video-amdgpu xf86-video-ati
-  xf86-video-dummy xf86-video-fbdev xf86-video-intel xf86-video-nouveau
-  xf86-video-openchrome xf86-video-sisusb xf86-video-vesa xf86-video-vmware
-  xf86-video-voodoo xorg-server xorg-xbacklight xorg-xinit xterm'
+# main(){
+#   # do some ENV checks
+#   sleep_clear 0
+#   check_uid
+#   check_env
+#   check_boot_mode
+# }
 
 #
 echo -ne "
@@ -127,10 +96,10 @@ echo "Enabling multilib repo"
 # Check if multilib repository exists in pacman.conf
 if grep -q "\[multilib\]" /etc/pacman.conf; then
     # Multilib repository exists, remove comment if it is commented out
-  sudo sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
+  sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
 else
     # Multilib repository does not exist, add it to pacman.conf
-  echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | sudo tee -a /etc/pacman.conf
+  echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf
 fi
 sleep 1s
 clear
@@ -140,10 +109,10 @@ echo "Enabling community repo"
 # Check if community repository exists in pacman.conf
 if grep -q "\[community\]" /etc/pacman.conf; then
     # Community repository exists, remove comment if it is commented out
-  sudo sed -i '/^\[community\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
+  sed -i '/^\[community\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
 else
     # Community repository does not exist, add it to pacman.conf
-  echo -e "[community]\nInclude = /etc/pacman.d/mirrorlist" | sudo tee -a /etc/pacman.conf
+  echo -e "[community]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf
 fi
 sleep 1s
 clear
@@ -385,10 +354,10 @@ echo "Enabling multilib repo"
 # Check if multilib repository exists in pacman.conf
 if grep -q "\[multilib\]" /etc/pacman.conf; then
     # Multilib repository exists, remove comment if it is commented out
-  sudo sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
+  sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
 else
     # Multilib repository does not exist, add it to pacman.conf
-  echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | sudo tee -a /etc/pacman.conf
+  echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf
 for
 clear
 
@@ -397,10 +366,10 @@ echo "Enabling community repo"
 # Check if community repository exists in pacman.conf
 if grep -q "\[community\]" /etc/pacman.conf; then
     # Community repository exists, remove comment if it is commented out
-  sudo sed -i '/^\[community\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
+  sed -i '/^\[community\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
 else
     # Community repository does not exist, add it to pacman.conf
-  echo -e "[community]\nInclude = /etc/pacman.d/mirrorlist" | sudo tee -a /etc/pacman.conf
+  echo -e "[community]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf
 for
 pacman -Syy --noconfirm pacman-contrib
 clear
@@ -552,6 +521,39 @@ install_packages() {
 
   #blackarch-slim-tools
   packages+='aircrack-ng amass arp-scan aquatone binwalk bulk-extractor bully burpsuite cewl chaos-client chntpw commix crackmapexec creddump crunch davtest dbd dirb dirbuster dmitry dns2tcp dnschef dnsenum dnsrecon dnsx enum4linux exiv2 exploitdb faradaysec fern-wifi-cracker ffuf fierce findomain fping gobuster guymager hashcat hashcat-utils hashdeep hashid hash-identifier hping hotpatch httpx hydra ike-scan inetsim iodine john kismet laudanum lbd legion lulzbuster macchanger magicrescue maltego maskprocessor massdns masscan metasploit msfdb mimikatz mitmproxy multimac nbtscan ncrack netdiscover netmask netsed netsniff-ng ngrep nikto nmap nuclei nuclei-templates onesixtyone openbsd-netcat ophcrack patator pdfid pdf-parser pipal pixiewps powersploit proxychains-ng proxytunnel proxify pth-toolkit ptunnel pwnat radare2 reaver rebind recon-ng redsocks responder rsmangler sakis3g samdump2 sbd scalpel scrounge-ntfs seclists set skipfish sleuthkit smbmap snmpcheck socat sploitctl spiderfoot spooftooph sqlmap ssldump sslscan sslsplit sslyze statsprocessor stunnel subfinder swaks tcpdump tcpick tcpreplay thc-ipv6 thc-pptp-bruter tor theharvester udptunnel unix-privesc-check voiphopper wafw00f wce webshells weevely wfuzz whatweb whois wifite windows-binaries winexe wireshark-qt wordlistctl wpscan zaproxy zdns zgrab2 zmap'
+
+  packages+='arch-install-scripts pkgfile'
+
+  packages+='bluez bluez-hid2hci bluez-tools bluez-utils'
+
+  packages+='chromium elinks firefox'
+
+  packages+='hexedit nano vim'
+
+  packages+='cifs-utils dmraid dosfstools exfat-utils f2fs-tools
+  gpart gptfdisk mtools nilfs-utils ntfs-3g partclone parted partimage'
+
+  packages+='ttf-dejavu ttf-indic-otf ttf-liberation xorg-fonts-misc'
+
+  packages+='amd-ucode intel-ucode'
+
+  packages+='linux-headers-lts'
+
+  packages+='acpi alsa-utils b43-fwcutter bash-completion bc cmake ctags expac
+  feh git gpm haveged hdparm htop inotify-tools ipython irssi
+  lsof mercurial mesa mlocate moreutils mpv p7zip rsync
+  rtorrent screen scrot smartmontools strace tmux udisks2 unace unrar
+  unzip upower usb_modeswitch usbutils zip zsh'
+
+  packages+='atftp bind-tools bridge-utils curl darkhttpd dhclient dhcpcd dialog
+  dnscrypt-proxy dnsmasq dnsutils fwbuilder gnu-netcat ipw2100-fw ipw2200-fw iw
+  iwd lftp nfs-utils ntp openconnect openssh openvpn ppp pptpclient rfkill
+  rp-pppoe socat vpnc wget wireless_tools wpa_supplicant wvdial xl2tpd'
+
+  packages+='rxvt-unicode xf86-video-amdgpu xf86-video-ati
+  xf86-video-dummy xf86-video-fbdev xf86-video-intel xf86-video-nouveau
+  xf86-video-openchrome xf86-video-sisusb xf86-video-vesa xf86-video-vmware
+  xf86-video-voodoo xorg-server xorg-xbacklight xorg-xinit xterm'
 },
 pacman -S --needed --noconfirm $packages
 sleep 1s
@@ -560,13 +562,13 @@ clear
 # Install needed pkgs and tools by AUR..
 echo "Installing needed pkgs and tools by AUR"
   # yay-bin: AUR helper
-  git clone https://aur.archlinux.org/yay-bin.git /aur/yay-bin
+  git clone https://aur.archlinux.org/yay-bin.git
   cd yay-bin
   makepkg -fsri
   cd ..
 
 # remove dir
-#rm -rf yay-bin
+rm -rf yay-bin
 
 # Install pkgs and tools by AUR..
 install_packages() {
@@ -637,7 +639,7 @@ sleep 2s
 clear
 
 #edit sudo
-echo 'Defaults env_keep += "HOME"' | sudo tee -a /etc/sudoers
+echo 'Defaults env_keep += "HOME"' | tee -a /etc/sudoers
 
 # Personal dotfiles
 echo "Setting up Personal dotfiles"
